// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiivPcLRwJyhju9FV0m7r_6MGcJto_xnQ',
    appId: '1:202648449417:web:b63ee4eaf8f4b8863c3158',
    messagingSenderId: '202648449417',
    projectId: 'trendtrove-e8f90',
    authDomain: 'trendtrove-e8f90.firebaseapp.com',
    storageBucket: 'trendtrove-e8f90.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5yOA81_14UXT1Dz3_fxS5fgAM-e27yho',
    appId: '1:202648449417:android:1adb5472213093063c3158',
    messagingSenderId: '202648449417',
    projectId: 'trendtrove-e8f90',
    storageBucket: 'trendtrove-e8f90.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXHlFR_3dfPvF0SrW1QANiYfaSoje2q3c',
    appId: '1:202648449417:ios:af8d7dfc8338e4c93c3158',
    messagingSenderId: '202648449417',
    projectId: 'trendtrove-e8f90',
    storageBucket: 'trendtrove-e8f90.appspot.com',
    androidClientId: '202648449417-fv5s1ooq92r5jee8lqd77ilog2avbush.apps.googleusercontent.com',
    iosClientId: '202648449417-jqf13ln7d9doc8p069u7rjvtl811m6uc.apps.googleusercontent.com',
    iosBundleId: 'com.example.trendtrove',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXHlFR_3dfPvF0SrW1QANiYfaSoje2q3c',
    appId: '1:202648449417:ios:15065df5d06ae51e3c3158',
    messagingSenderId: '202648449417',
    projectId: 'trendtrove-e8f90',
    storageBucket: 'trendtrove-e8f90.appspot.com',
    androidClientId: '202648449417-fv5s1ooq92r5jee8lqd77ilog2avbush.apps.googleusercontent.com',
    iosClientId: '202648449417-ge689oq89eodq0427slv3jtbgralftt9.apps.googleusercontent.com',
    iosBundleId: 'com.example.trendtrove.RunnerTests',
  );
}
